apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"



