apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources: 
        requests:
          memory: "5Gi"
          cpu: "500m"
        limits:
          memory: "5Gi"
          cpu: "500m"



