apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: red
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.153.10
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



